Tickets/dm 39012
lsst-ts/ts_atmcssimulator pull request #45
Opened 2023-05-30 14:57 UTC by wvreeven

2023-05-30 21:04 UTC, r-owen requested changes
I am very excited about this improvement. It will be wonderful to be able to use Python to run the ATMCS, and this is a big step in that direction.

My main concern is that the CSC is a simulator constructor argument, and it seems to be intended to provide structs to save and report data. Please consider writing data classes instead (or some other custom classes).

My only other significant concerns are:
* I might have found a bug in set_instrument_port (certainly code that could be clarified, even if I originally wrote it).
* Using mutable data as default values for arguments.

2023-05-31 17:59 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        }
Done

2023-05-31 18:04 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        )
I created DM-39469 for that and added a TODO.

2023-05-31 18:57 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        min_commanded_position: np.ndarray = np.array(
This is copied one on one from the original code. I also opened DM-38912 to improve this as is mentioned by several TODOs in this file.

2023-05-31 19:02 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +                minimum=self.min_commanded_position.tolist(),
No reason at all. I modified this to `list(...)`.

2023-05-31 19:03 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            await self.write_fail_response(sequence_id=sequence_id)
Unfortunately not. I will discuss that with Te-Wei (who designed the LabVIEW TCP/IP code) to ask why and also to ask if that can be included.

2023-05-31 19:06 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            self._axis_enabled[Axis.NA2] = False
This, too, is copied one on one from the original code. If this is a bug then it was already present in the CSC.

2023-05-31 19:08 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +    def __init__(self, csc: ATMCSCsc) -> None:
I removed the constructor argument and introduced dataclasses instead.

2023-05-31 19:22 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            await self.write_fail_response(sequence_id=sequence_id)
Te-Wei has a suggestion how to solve this, which involves sending a second message after the `fail` message with the reason. Unfortunately the current `ts_labview_tcp_json` project doesn't support adding a reason easily. I will discuss this with Patricio and then add it. I'll create a ticket for that in due time.

2023-05-31 21:21 UTC, r-owen commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            await self.write_fail_response(sequence_id=sequence_id)
It's unfortunate not to be able to include all the related information in the same message, but this sounds better than nothing having the reason available.

2023-06-01 14:51 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        m3_in_position = self.m3_in_position(utils.current_tai())
Once again I am copying code from the CSC and the corresponding methods didn't have a doc string there either. Having said that, I am following up on all your suggestions.

2023-06-01 15:41 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        if not self._tracking_enabled:
I have made all arguments explicit.

2023-06-01 16:27 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        #  set the CSC to FAULT after a certain period was passed but there is
I retained the original code with a new TODO indicating that a feedback mechanism from the ATMCS to the CSC needs to be implemented. Perhaps a new event (not a SAL event!!!) message would be sufficient so the CSC can take proper action. This certainly is future work.

2023-06-01 16:29 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            return
Again, this is copied one on one from the original code. I agree that it needs to be revised but that is future work.

2023-06-01 16:29 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        # self._set_tracking_timer(restart=True)
TODO removed. See my previous comment about possibly introducing a new event message.

2023-06-01 18:18 UTC, r-owen approved these changes
I have a few smaller cleanups I hope you will consider before merging, the main one being to use a different way of specifying the default for your new dataclasses (simple -- a global search/replace plus removing the `__post_init__` methods).

2023-06-01 18:18 UTC, r-owen commented on python/lsst/ts/atmcssimulator/dataclasses.py
> +    index : int
Please fix the documented types to match the actual type (int | None in this case)

2023-06-01 18:18 UTC, r-owen commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +        min_commanded_position: np.ndarray = np.array(
Scary. I didn't spend a lot of time on this code, but still...

2023-06-01 18:18 UTC, r-owen commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            self._axis_enabled[Axis.NA2] = False
Actually this is correct; I just forgot why it was done. When the tertiary mirror is moved then the NA1 and NA2 rotators are disabled.

If you are willing, please aded a code comment explaining that.

2023-06-01 18:18 UTC, r-owen commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            return
Fair enough and best left until we know what the real controller does.

2023-06-01 18:18 UTC, r-owen commented on python/lsst/ts/atmcssimulator/mcs_simulator.py
> +            self._axis_enabled[Axis.NA2] = False
Actually this is correct; I just forgot why it was done. When the tertiary mirror is moved then the NA1 and NA2 rotators are disabled.

If you are willing, please aded a code comment explaining that.

2023-06-01 19:32 UTC, wvreeven commented on python/lsst/ts/atmcssimulator/dataclasses.py
> +    elevationEncoderRaw: list[float] = field(default_factory=list)
Thanks. This is a much better solution and it wasn't clear to me from the Python docs that this is possible.

2023-06-01 19:48 UTC, merged